
###
GET http://localhost:8888/auth/public
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
POST http://localhost:8888/auth/tokens/login
Content-Type: application/json

{
  "mail": "admin@admin.com",
  "password": "pTWER-gYG5-ohom-qsZg"
}
> {%
client.global.set("auth_token_admin", response.body.accessToken);
client.global.set("refr_token_admin", response.body.refreshToken);

client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###

PATCH http://localhost:8888/auth/users/password
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "oldPassword": "pTWER-gYG5-ohom-qsZg",
  "newPassword": "admin1"
}
> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST http://localhost:8888/auth/tokens/login
Content-Type: application/json

{
  "mail": "admin@admin.com",
  "password": "admin1"
}
> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###


POST http://localhost:8888/auth/tokens/login
Content-Type: application/json

{
  "mail": "admin@youmail.com",
  "password": "admin1"
}
> {%
  client.test("Request executed successfully", function() {
  client.assert(response.status === 404, "Response status is not 404");
});
%}
###


POST http://localhost:8888/auth/tokens/claim
Content-Type: application/json

{
  "mail": "toto@mail.com",
  "password": "toto"
}
> {% client.global.set("auth_token_toto", response.body.accessToken);
     client.global.set("refr_token_toto", response.body.refreshToken);
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201 - CREATED");
});
%}
###

POST http://localhost:8888/auth/tokens/claim
Content-Type: application/json

{
  "mail": "toto@.com",
  "password": "toto"
}
> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 409, "Response status is not 409");
});
%}

###


PATCH http://localhost:8888/auth/users/mail
Content-Type: application/json
Authorization: Bearer {{auth_token_toto}}

{
  "newmail": "toto@youmail.com",
  "password": "toto"
}
> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200 - OK");
});
%}

###
POST http://localhost:8888/auth/tokens/login
Content-Type: application/json

{
  "mail": "toto@youmail.com",
  "password": "toto"
}

> {%
  client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not OK");
});
%}

###
POST http://localhost:8888/auth/tokens/claim
Content-Type: application/json

{
  "mail": "user2@mail.com",
  "password": "toto"
}
> {% client.global.set("auth_token_toto2", response.body.accessToken);
     client.global.set("refr_token_toto2", response.body.refreshToken);
     client.test("Request executed successfully", function() {
     client.assert(response.status === 201, "Response status is not 201 - CREATED");
     });
 %}

###
GET http://localhost:8888/auth/tokens/login
Content-Type: application/json
Authorization: Bearer {{auth_token_toto2}}



> {%
  client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not OK");
});
%}

###
GET http://localhost:8888/auth/admin/users/2
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}



> {%
  client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not OK");
});
%}

###
GET http://localhost:8888/auth/users/me
Content-Type: application/json
Authorization: Bearer {{auth_token_toto}}

> {%
  client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not OK");
});
%}

###

POST http://localhost:8888/auth/tokens/login
Content-Type: application/json

{
  "mail": "user2@mail.com",
  "password": "toto"
}
> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200 - OK");
});
%}

###

POST http://localhost:8888/auth/tokens/login
Content-Type: application/json

{
  "mail": "toto@mail.com",
  "password": "toto"
}

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 404, "Response status is not 404 - KO");
});
%}

###
GET http://localhost:8888/auth/domains
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200 - OK");
});
%}

###
POST http://localhost:8888/auth/admin/domains
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "domain": "rumail.ru"
}
> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 201, "Response status is not 201 - CREATED");
});
%}

###
GET http://localhost:8888/auth/domains
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200 - OK");
});
%}

###
DELETE http://localhost:8888/auth/admin/domains
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "domain": "rumail.ru"
}
> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 204, "Response status is not 204 - NO CONTENT ");
});
%}

###
GET http://localhost:8888/auth/domains
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200 - OK");
});
%}

###

POST http://localhost:8888/auth/admin/domains
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "domain": "rumail.ru"
}
> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 201, "Response status is not 201 - CREATED");
});
%}

###
POST http://localhost:8888/auth/tokens/claim
Content-Type: application/json

{
  "mail": "user3@rumail.ru",
  "password": "rupassword"
}
> {%
     client.test("Request executed successfully", function() {
     client.assert(response.status === 409, "Response status is not 409 - CONFLICT");
     });
 %}

###

GET http://localhost:8888/auth/tokens/refresh
Content-Type: application/json
Authorization: Bearer {{refr_token_toto}}


> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200 - OK");
});
%}
###


PATCH http://localhost:8888/auth/admin/users/2/roles
Content-Type: application/json
//admin token here
Authorization: Bearer {{auth_token_admin}}

{
  "roles": [
    "ADMIN",
    "USER"
  ]
}

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200 - OK");
});
%}

###BAN TEST
POST http://localhost:8888/auth/tokens/claim
Content-Type: application/json

{
  "mail": "userToBan@mail.com",
  "password": "utb"
}
> {% client.global.set("auth_token_bu", response.body.accessToken);
     client.global.set("refr_token_bu", response.body.refreshToken);
     client.test("Request executed successfully", function() {
     client.assert(response.status === 201, "Response status is not 201 - CREATED");
     });
 %}


### BAN USER
POST http://localhost:8888/auth/admin/users/4/ban
Content-Type: application/json
Authorization:Bearer {{auth_token_admin}}


{
  "reason": "SPAM"
}
> {%
     client.test("Request executed successfully", function() {
     client.assert(response.status === 200, "Response status is not 200 - OK");
     });
 %}

### TEST LOG user ban
POST http://localhost:8888/auth/tokens/login
Content-Type: application/json

{
  "mail": "userToBan@mail.com",
  "password": "utb"
}
> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 403, "Response status is not 403 - Forbidden");
});
%}

###

GET http://localhost:8888/auth/tokens/refresh
Content-Type: application/json
Authorization: Bearer {{refr_token_bu}}


> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 403, "Response status is not 403 - Forbidden");
});
%}

### UNBAN USER
DELETE http://localhost:8888/auth/admin/users/4/ban
Content-Type: application/json
Authorization:Bearer {{auth_token_admin}}

> {%
     client.test("Request executed successfully", function() {
     client.assert(response.status === 204, "Response status is not 204 - NO CONTENT");
     });
 %}

### TEST LOG user UNban
POST http://localhost:8888/auth/tokens/login
Content-Type: application/json

{
  "mail": "userToBan@mail.com",
  "password": "utb"
}
> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200 - OK");
});
%}

###REFRESH usr unban

GET http://localhost:8888/auth/tokens/refresh
Content-Type: application/json
Authorization: Bearer {{refr_token_bu}}


> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200 - OK");
});
%}

###


DELETE http://localhost:8888/auth/admin/clean
Content-Type: application/json
Authorization:Bearer {{auth_token_admin}}

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 204, "Response status is not 204 - NO CONTENT");
});
%}
###

DELETE http://localhost:8888/auth/users/me
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "password": "admin1"
}

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 404, "Response status is not 404 - NOT FOUND ");
});
%}
###
POST http://localhost:8888/auth/tokens/login
Content-Type: application/json

{
  "mail": "admin@youmail.com",
  "password": "admin1"
}

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 404, "Response status is not 404 - NOT FOUND ");
});
%}