GET http://localhost:8888/auth/public
Content-Type: application/json

###
POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "mail": "admin@admin.com",
  "password": "IpM1p-XJho-mTj7-EGqL"
}

###
POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "mail": "admin@admin.com",
  "password": "admin1"
}

###

POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "mail": "admin@mail.com",
  "password": "admin1"
}

###
PATCH http://localhost:8888/auth/login/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIxIiwic3ViIjoiMSIsImlhdCI6MTU4NzMwMTg2OCwiZXhwIjoxNTg3MzA1NDY4LCJ0eXBlIjoiQUNDRVNTIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl19.RXTMPBurB2d_CFOSOGmaW4hmedZPvnDFZhsLZow8zPsVek4XLpes5A30oHNHQx1kWuHMSQqfJ1Y_AC0W0oxE5MOncIYmrAtW_K82evRbq1uYMlQYtmzmMGhOlAHNDNZ6_f8nQ_YRgRyZboKYkhJETAUbcY50BZD2bAU5hifDLJ0HvY3M7IhXTk48tEgLk5xYURONJyW91HfPBDpFtJcDp3GzkulMArRl8-fO1Ri9v3dPe9mCIKxjAQPrhLU7QpPJFMju-lt_pP3Id2wBPdsDKBOluZ6tPQC3mJhDk-QIXLiJjlPC8lVmewBditk_dn1G3eIi_ESJsPSCQuLPotfZCw

{
  "oldPassword": "ohDpM-HJBI-o93M-8UxI",
  "newPassword": "admin1"
}

###

PATCH http://localhost:8888/auth/login/mail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIxIiwic3ViIjoiMSIsImlhdCI6MTU4NzMwMTg2OCwiZXhwIjoxNTg3MzA1NDY4LCJ0eXBlIjoiQUNDRVNTIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl19.RXTMPBurB2d_CFOSOGmaW4hmedZPvnDFZhsLZow8zPsVek4XLpes5A30oHNHQx1kWuHMSQqfJ1Y_AC0W0oxE5MOncIYmrAtW_K82evRbq1uYMlQYtmzmMGhOlAHNDNZ6_f8nQ_YRgRyZboKYkhJETAUbcY50BZD2bAU5hifDLJ0HvY3M7IhXTk48tEgLk5xYURONJyW91HfPBDpFtJcDp3GzkulMArRl8-fO1Ri9v3dPe9mCIKxjAQPrhLU7QpPJFMju-lt_pP3Id2wBPdsDKBOluZ6tPQC3mJhDk-QIXLiJjlPC8lVmewBditk_dn1G3eIi_ESJsPSCQuLPotfZCw

{
  "newmail": "admin@mail.com",
  "password": "admin1"
}

###


POST http://localhost:8888/auth/claim
Content-Type: application/json

{
  "mail": "toto@mail.com",
  "password": "toto"
}

###

POST http://localhost:8888/auth/claim
Content-Type: application/json

{
  "mail": "toto@.com",
  "password": "toto"
}
> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 409, "Response status is not 409");
});
%}

###
POST http://localhost:8888/auth/claim
Content-Type: application/json

{
  "mail": "user2@mail.com",
  "password": "toto"
}

###
POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "mail": "user2@mail.com",
  "password": "toto"
}

###

POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "mail": "toto@mail.com",
  "password": "toto"
}

###

GET http://localhost:8888/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJJU1NVRVIiLCJqdGkiOiI0Iiwic3ViIjoiMSIsImlhdCI6MTU4ODE3ODQ2NCwiZXhwIjoxNTg4MjY0ODY0LCJ0eXBlIjoiUkVGUkVTSCJ9.OhNcWSeA6SIPvlSyTgHrfI0DdEVY41_LLj4QJ9SwghOYDznT9pW9px2ZANx6KB-PcckukX7Z1W8IXbUjf8On8WfMIdiUuk62ubIkP6Kr5m4__S4TxkJb_3y5RozYOVe4rzJSpIsuhyNi4z9pT2GFz0g2J97GycsgSLwRf6Q-XQY3A4Ss-GLPYI84XhmIz-WdEGZHvUAPViuZckQtG0N2te_JDAaaKbS1Hr1qSNJdtH4qklkt3_ijvfez07MzrWR6kaOmHkwGeFw0He_5uYIUMu_EJrR_SbnUACC9jpsokLsDGtVMauWqALH_EjN-7GB2dRi1Ctg_xq6MEMV_Yr71TA

###


PATCH http://localhost:8888/auth/claim/2/roles
Content-Type: application/json
//admin token here
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJJU1NVRVIiLCJqdGkiOiI1Iiwic3ViIjoiMSIsImlhdCI6MTU4ODE3ODQ3OSwiZXhwIjoxNTg4MTgyMDc5LCJ0eXBlIjoiQUNDRVNTIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl19.ZWmlUtxh7sc9tbk6cxXKciqlxeIAUH9JLqFK8YLuH1UR6xEbVLKNNbxJ7rDmkyf28l8d2o7mRgEK9bCXHmK4rk0zCjnhis5---vZjmQKQVRzqo0eDov4vMBkCz4ADKox5mJt20VgE8TDkLgnpPJRPrPsiiDqvKsOoYrGWgsparfp6-p_oKTBZY69Urg5LB87jEuP760pSwdjwfpFsXPQhqj7QPz3YduyaA1SHB_XAN47ci0-kDwIGC-HOe9o4oJixlSMwuFfi1iESSagzkqlrXGhHV5XL7pbu1ZQ2ljJcWWqkOWTyeg2X2_uc09mMOEEt2fJur06AOJKRIW22uC9EA

[
  "admin",
  "user"
]

###
DELETE http://localhost:8888/auth/clean
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIxMSIsInN1YiI6IjEiLCJpYXQiOjE1ODczMDIwMzYsImV4cCI6MTU4NzMwNTYzNiwidHlwZSI6IkFDQ0VTUyIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdfQ.avD0Rllvi2iaWdlSkwdE-_aNxDhrfKpmYdfbBOcLVtWXBG4fDH-Z9q6rFGtmIiujqouqWNJEahULirj4pKTpWVyeSgr5Oxk9XeK5Khe5BqUqr_TSkN8f_PlSpyoDuaiZBs8wYXYDlNeSkTb37QYRczWIbrEWyLBF1IxDCPyiBhiTIYimVVAjCyMDymClOXfELffWZ3o2QIJrOgfNv0RyBmYuOpRC-F4hl8Am4AwPpt1pU1jbIfPknkS6YWJLTMSXnmCrMlXR66uuUlA9XgXjc3goSRlCNTMyrCHdGNZJNNY2h3SO_s04AG4h3OC5wDRu_CFUlEu2Z0RyVCyJi3064A
###