
###
GET http://localhost:8888/auth/public
Content-Type: application/json

###
POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "mail": "admin@admin.com",
  "password": "mdpadmin"
}
> {% client.global.set("auth_token_admin", response.body.accessToken); %}
###

PATCH http://localhost:8888/auth/login/password
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "oldPassword": "mdpadmin",
  "newPassword": "admin1"
}

###

POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "mail": "admin@admin.com",
  "password": "admin1"
}

###



PATCH http://localhost:8888/auth/login/mail
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "newmail": "admin@youmail.com",
  "password": "admin1"
}

###

POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "mail": "admin@youmail.com",
  "password": "admin1"
}

###


POST http://localhost:8888/auth/claim
Content-Type: application/json

{
  "mail": "toto@mail.com",
  "password": "toto"
}

###

POST http://localhost:8888/auth/claim
Content-Type: application/json

{
  "mail": "toto@.com",
  "password": "toto"
}
> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 409, "Response status is not 409");
});
%}

###
POST http://localhost:8888/auth/claim
Content-Type: application/json

{
  "mail": "user2@mail.com",
  "password": "toto"
}

###
POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "mail": "user2@mail.com",
  "password": "toto"
}

###

POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "mail": "toto@mail.com",
  "password": "toto"
}

###

GET http://localhost:8888/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJJU1NVRVIiLCJqdGkiOiIyIiwic3ViIjoiMSIsImlhdCI6MTU4ODUyNjEyMSwiZXhwIjoxNTg4NjEyNTIxLCJ0eXBlIjoiUkVGUkVTSCJ9.EhoSSbbKNx2vNW3SPzVU36IT4imhz23f_UAZwXNoIhfKWvpEQqjAkMMHP_wRdy2Ra6eQcjJpZB7eUoYuuHf5rGjA3cX3voo0hHmClextf2zlY0ewDdfp9zsL5i663rOHPY4nU527Fr-Cog_OriBvbA69aXPBO36LKE7do7cqtY9zZovGmggRThpPFdCk0uVwqflCECEpTnxa85s6pozkF2eqJO7tbwXmXk_yXDKmrMiFpl0gjb5tbJeLx5U1AfdNTqV5FLTQ8mKZ-e_in9-qhTTwi_qUZfFGZZ3hRmAI31RVMX4yfsKTf2WhoNDh5yRz43y2aTt7iBpnc7bHv3BBDQ
###


PATCH http://localhost:8888/auth/claim/2/roles
Content-Type: application/json
//admin token here
Authorization: Bearer {{auth_token_admin}}

{
  "roles": [
    "ADMIN",
    "USER"
  ]
}


###
DELETE http://localhost:8888/auth/clean
Content-Type: application/json
Authorization:Bearer {{auth_token_admin}}


###

DELETE http://localhost:8888/auth/login
Content-Type: application/json
Authorization: Bearer {{auth_token_admin}}

{
  "password": "mdpadmin"
}


###