package com.example.auth.server.model.entities.enums;

/**
 * @autor Vincent
 * @date 30/07/2020
 */
public enum LogStatus {
	REGISTRATION,
	REFRESHING,
	LOGING_SUCCESSFULL,
	BAD_PASSWORD,
	ROLES_UPDATE,
	CLAIM_PASSWORD_RESET_TOKEN,
	UPDATE_PASSWORD_BY_RESET,
	UPDATE_PASSWORD,
	UPDATE_MAIL,
	BAN,
	UNBAN,
	ADMIN_USER_ROLES_UPDATE,
	ADMIN_BAN_USER,
	ADMIN_UNBAN_USER
}
